function parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p'
}

setopt PROMPT_SUBST
export PROMPT='%{%F{102}%}%n %{%F{224}%}%~ %{%F{151}%}$(parse_git_branch) %{%F{normal}%}🐾 %{%f%} '
